import { useEffect, useState } from 'react'
import type { TodayViewModel } from '../../shared/api'
import { getRendererApi } from './api'
import { EmptyState } from './components/EmptyState'
import { RefreshButton } from './components/RefreshButton'
import { useI18n } from './i18n'

function input(){const timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone;const values=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(p=>[p.type,p.value]));return{localDate:`${values['year']}-${values['month']}-${values['day']}`,timeZone}}
export function MenuBarApp():React.JSX.Element{const{t,number,time}=useI18n();const[today,setToday]=useState<TodayViewModel|null>(null);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const load=async()=>{const r=await getRendererApi().getToday(input());if(r.ok)setToday(r.value);setLoading(false)};useEffect(()=>{void getRendererApi().getToday(input()).then(r=>{if(r.ok)setToday(r.value);setLoading(false)})},[]);const refresh=async()=>{setRefreshing(true);await getRendererApi().refreshNow();await load();setRefreshing(false)};if(loading)return <main className="menu-app"><p>{t('loadingToday')}</p></main>;const sessions=today?.overall?.sessionCount??0;return <main className="menu-app"><header><div><span>{today?.localDate}</span><h1>{t('menuTitle')}</h1><p>{today?.coveredAt?t('coveredUntil',{time:time(new Date(today.coveredAt))}):t('localStatistics')}</p></div><RefreshButton refreshing={refreshing} onRefresh={()=>void refresh()}/></header>{sessions===0?<EmptyState/>:<section className="menu-summary"><strong>{number(sessions)}</strong><span>{t('nativeSessions')}</span><p>{today?.intensity?.explanation}</p></section>}<button className="open-client-button" onClick={()=>void getRendererApi().openClient()} type="button">{t('openFullClient')}</button><p className="menu-notice">{t('statisticsNotice')}</p></main>}
