import { useEffect, useState } from 'react'
import type { RefreshReport, TodayViewModel } from '../../shared/api'
import { getRendererApi } from './api'
import { EmptyState } from './components/EmptyState'
import { RefreshButton } from './components/RefreshButton'
import { useI18n } from './i18n'

function input(){const timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone;const values=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(p=>[p.type,p.value]));return{localDate:`${values['year']}-${values['month']}-${values['day']}`,timeZone}}
export function MenuBarApp():React.JSX.Element{const{t,number,time}=useI18n();const[today,setToday]=useState<TodayViewModel|null>(null);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[message,setMessage]=useState<{text:string;alert:boolean}|null>(null);const load=async()=>{try{const r=await getRendererApi().getToday(input());if(r.ok)setToday(r.value)}finally{setLoading(false)}};useEffect(()=>{void load()},[]);const describe=(report:RefreshReport)=>{if(report.status==='skipped')return{text:t('refreshSkipped'),alert:false};if(report.status==='failed')return{text:t('refreshFailed'),alert:true};if(report.failed>0)return{text:t('refreshPartial'),alert:true};if(report.providerResults.length>0&&report.providerResults.every(result=>result.status==='unsupported'))return{text:t('refreshUnsupported'),alert:false};const changes=report.inserted+report.updated;return{text:changes>0?t('refreshChanged',{count:number(changes)}):t('refreshNoChange'),alert:false}};const refresh=async()=>{setRefreshing(true);try{const r=await getRendererApi().refreshNow();setMessage(r.ok?describe(r.value):{text:t('refreshFailed'),alert:true})}catch{setMessage({text:t('refreshFailed'),alert:true})}finally{try{await load()}finally{setRefreshing(false)}}};if(loading)return <main className="menu-app"><p>{t('loadingToday')}</p></main>;const sessions=today?.overall?.sessionCount??0;return <main className="menu-app"><header><div><span>{today?.localDate}</span><h1>{t('menuTitle')}</h1><p>{today?.coveredAt?t('coveredUntil',{time:time(new Date(today.coveredAt))}):t('localStatistics')}</p></div><RefreshButton refreshing={refreshing} onRefresh={()=>void refresh()}/></header>{message&&<p className={message.alert?'refresh-feedback refresh-feedback--alert':'refresh-feedback'} role={message.alert?'alert':'status'}>{message.text}{message.alert&&` ${t('preservedData')}`}</p>}{sessions===0?<EmptyState/>:<section className="menu-summary"><strong>{number(sessions)}</strong><span>{t('nativeSessions')}</span><p>{today?.intensity?.explanation}</p></section>}<button className="open-client-button" onClick={()=>void getRendererApi().openClient()} type="button">{t('openFullClient')}</button><p className="menu-notice">{t('statisticsNotice')}</p></main>}
