import { useCallback, useEffect, useState } from 'react'
import type { RefreshReport, RefreshState, TodayViewModel } from '../../../shared/api'
import { getRendererApi } from '../api'
import { EmptyState } from '../components/EmptyState'
import { IntensityHeader } from '../components/IntensityHeader'
import { ProviderActivityList } from '../components/ProviderActivityList'
import { RecentSessions } from '../components/RecentSessions'
import { RefreshButton } from '../components/RefreshButton'
import { useI18n } from '../i18n'
function todayInput(){const timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone;const parts=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const values=Object.fromEntries(parts.map(p=>[p.type,p.value]));return{localDate:`${values['year']}-${values['month']}-${values['day']}`,timeZone}}
export function TodayPage(): React.JSX.Element {
 const {t,number,time}=useI18n(); const [today,setToday]=useState<TodayViewModel|null>(null);const[error,setError]=useState(false);const[loading,setLoading]=useState(true);const[refreshState,setRefreshState]=useState<RefreshState>({status:'idle'});const[refreshMessage,setRefreshMessage]=useState<{text:string;alert:boolean}|null>(null)
 const load=useCallback(async()=>{try{const r=await getRendererApi().getToday(todayInput());if(r.ok){setToday(r.value);setError(false)}else setError(true)}catch{setError(true)}finally{setLoading(false)}},[])
 useEffect(()=>{void Promise.resolve().then(load);return getRendererApi().onRefreshState(setRefreshState)},[load])
 const describe=(report:RefreshReport)=>{if(report.status==='skipped')return{text:t('refreshSkipped'),alert:false};if(report.status==='failed')return{text:t('refreshFailed'),alert:true};if(report.failed>0)return{text:t('refreshPartial'),alert:true};if(report.providerResults.length>0&&report.providerResults.every(result=>result.status==='unsupported'))return{text:t('refreshUnsupported'),alert:false};const changes=report.inserted+report.updated;return{text:changes>0?t('refreshChanged',{count:number(changes)}):t('refreshNoChange'),alert:false}}
 const refresh=async()=>{setRefreshState({status:'scanning'});try{const r=await getRendererApi().refreshNow();setRefreshMessage(r.ok?describe(r.value):{text:t('refreshFailed'),alert:true})}catch{setRefreshMessage({text:t('refreshFailed'),alert:true})}finally{await load();setRefreshState({status:'idle'})}}
 if(loading)return <div className="page-state" role="status"><div className="skeleton skeleton-title"/><div className="skeleton skeleton-card"/><span>{t('loadingToday')}</span></div>
 if(!today)return <div className="page-state"><h1>{t('loadFailed')}</h1>{error&&<p>{t('preservedData')}</p>}<button className="primary-button" onClick={()=>void load()} type="button">{t('retry')}</button></div>
 const overall=today.overall, providers=today.providers??[];const metric=(v:number|null|undefined)=>v==null?t('unavailable'):number(v)
 return <div className="page-content"><header className="page-header"><div><p className="section-label">{today.localDate??t('todayNav')}</p><h1>{t('todayActivity')}</h1><p>{today.coveredAt?t('coveredUntil',{time:time(new Date(today.coveredAt))}):t('localStatistics')}</p></div><RefreshButton refreshing={refreshState.status==='scanning'} onRefresh={()=>void refresh()}/></header>{refreshMessage&&<div className={refreshMessage.alert?'error-banner':'notice'} role={refreshMessage.alert?'alert':'status'}>{refreshMessage.text}{refreshMessage.alert&&<span>{t('preservedData')}</span>}</div>}{overall&&overall.sessionCount>0&&today.intensity?<><IntensityHeader intensity={today.intensity}/><section className="metric-grid" aria-label={t('todaySummary')}><article><span>{t('nativeSessions')}</span><strong>{number(overall.sessionCount)}</strong></article><article><span>{t('effectiveInteractions')}</span><strong>{metric(overall.interactionCount)}</strong></article><article><span>{t('tokenUsage')}</span><strong>{metric(overall.tokenUsage)}</strong></article><article><span>{t('activeDuration')}</span><strong>{overall.activeDurationSeconds==null?t('unavailable'):t('seconds',{value:number(overall.activeDurationSeconds)})}</strong></article></section><ProviderActivityList providers={providers}/><RecentSessions sessions={today.recentSessions??[]}/></>:<EmptyState/>}<aside className="notice"><strong>{t('statisticsOnly')}</strong><p>{t('statisticsNotice')}</p></aside></div>
}
